name: run-go-test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  run-go-test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Test
        run: go test ./..
